name: Test

on:
  push:
    branches: [ main, feature/*, release/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test imports
        run: |
          python -c "
          try:
              from src.embedding_provider import get_embed_model, get_embed_model_from_env
              from src.llamaindex_processor import RAGEngine  
              from src.mcp_server import RAGMCPServer
              print('✅ All imports successful')
          except Exception as e:
              print(f'❌ Import failed: {e}')
              exit(1)
          "